# Generated by Django 5.2.4 on 2025-07-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_delete_coreadminemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Google Form or registration link', null=True),
        ),
    ]
