# Generated by Django 5.2.4 on 2025-07-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sociallink'),
    ]

    operations = [
    ]
